# nome da pipeline
name: Run Basic Tests

# em que momento ela será executada
on:
  pull_request:
    branches: [master]

jobs:
  # o que vai ser feito nessa pipeline
  # só teremos um job: rodar os testes
  cypress-run:
    # máquina que será executado
    runs-on: ubuntu-latest

    # passo a passo para rodar os testes
    steps:
      # clone do projeto
      - name: Checkout/Clone do projeto
        uses: actions/checkout@v3
      
      # exemplo de execução no terminal
      # quando eu qro executar qualquer coisa no terminal, 
      # eu simplesmente dou um run e boto o comando que eu qro
      - name: instalar dependencias do projeto
        run: npm install

      # Execução e configuração do projeto
      - name: Run testes
        uses: cypress-io/github-action@v6
        with:
          redord: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
